user:
  firstName: nive
from:
  address: chennai
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true  
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
