user:
  firstName: nivethitha ezhil

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true  
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
